[project]
name = "plotting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "August Hauge Smevold", email = "august.hauge.smevold@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "h5py>=3.16.0",
    "matplotlib>=3.11.1",
    "scipy>=1.18.1",
]

[project.scripts]
plotting = "plotting:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
